# podman compose file for running paperless from the Docker Hub.
# This file contains everything paperless needs to run.
# Paperless supports amd64, arm and arm64 hardware.
#
# For more extensive installation and update instructions, refer to the
# documentation: https://docs.paperless-ngx.com/

services:
  broker:
    image: docker.io/library/redis:8
    container_name: paperless-redis-broker
    restart: always
    volumes:
      - $HOME/paperless/redisdata:/data
    networks:
      - paperless-net      
  db:
    image: docker.io/library/mariadb:11
    container_name: paperless-mariadb
    restart: always
    volumes:
      - $HOME/paperless/dbdata:/var/lib/mysql
    networks:
      - paperless-net      
    environment:
      MARIADB_HOST: paperless
      MARIADB_DATABASE: paperless
      MARIADB_USER: paperless
      MARIADB_PASSWORD: paperless
      MARIADB_ROOT_PASSWORD: paperless
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-webserver
    restart: always
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "8085:8000" # map free port here i.Ex. 8080:8000, 8081:8000...
    networks:
      - paperless-net
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: db
      PAPERLESS_DBUSER: paperless # only needed if non-default username
      PAPERLESS_DBPASS: paperless # only needed if non-default password
      PAPERLESS_DBPORT: 3306
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      # Examples, adjust to your local server name/IP
      PAPERLESS_CSRF_TRUSTED_ORIGINS: "http://Z890.fritz.box"
      PAPERLESS_ALLOWED_HOSTS: "localhost,Z890.fritz.box,192.168.179.101"
      PAPERLESS_SECRET_KEY: 8ACmK584EUKK7D5E73U715yRSVo9VCNs
      USERMAP_UID: 1000
      USERMAP_GID: 1000
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_OCR_LANGUAGE: deu+eng
    volumes:
      - $HOME/paperless/data:/usr/src/paperless/data
      - $HOME/paperless/media:/usr/src/paperless/media
      - $HOME/paperlessexport:/usr/src/paperless/export
      - $HOME/paperless/consume:/usr/src/paperless/consume
  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.20
    container_name: paperless-gotenberg
    restart: always
    networks:
      - paperless-net    
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
  tika:
    image: docker.io/apache/tika:latest
    container_name: paperless-tika
    restart: unless-stopped
    networks:
      - paperless-net    
networks:
  paperless-net:
    name: paperless-net
    driver: bridge
