services:
   db:
     image: mysql:5.7
     container_name: mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress
     volumes:
       - $HOME/wordpress/db_data:/var/lib/mysql       
   wordpress:
     image: wordpress:latest
     container_name: wordpress
     ports:
       - 8082:80
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     volumes:
       - $HOME/wordpress/wp_data:/var/www/html
